spring.application.name=gaminghouse

spring.datasource.url=jdbc:postgresql://localhost:5432/gaminghouse
spring.datasource.username=postgres
spring.datasource.password=DB_PASSWORD
spring.jpa.hibernate.ddl-auto=update