spring.application.name=gaminghouse

spring.datasource.url=jdbc:postgresql://localhost:5432/gaminghouse
spring.datasource.username=postgres
spring.datasource.password=13050904
spring.jpa.hibernate.ddl-auto=update